### PR TITLE
318- Blog CSS

### PR DESCRIPTION
**Pull request by MayaGans**
# Updates:

- Move footer below main
- Move some nav links to footer, and footer links to nav
- Increase margins and whitespace
- Change fonts
- Remove front matter from block documentation 
- GUIDE now contains all block documentation with RHS sticky menu
- `GUIDE` produces a dropdown of languages which direct to either `en/guide` or `es/guide`
- `FAQ` produces a dropdown of languages which direct to either `en/FAQ` or `es/FAQ`
- Add img folder with block svgs to each language and use those extensions inside the index.md files

### CODE REVIEW

**Comment by DarkMetroid** [comment]
Looks like `docs/styles/js-doc-default.css` imports the OpenSans so that'd explain it. If we copy the @font-face stuff over to `base.scss` it should work.

**Comment by MayaGans** [comment]
Alright so I made a sticky right hand side nav bar inside `en/guide.md` and `es/guide.md` but these pages need some help..... 

# 1 

I tried using

```
<h1>Data</h1>
{% include_relative data/index.md %}
<h1>Transforms</h1>
{% include_relative transform/index.md %}
<h1>Plots</h1>
{% include_relative plot/index.md %}
<h1>Statistics</h1>
{% include_relative stats/index.md %}
<h1>Operations</h1>
{% include_relative op/index.md %}
<h1>Values</h1>
{% include_relative value/index.md %}
<h1>Combining</h1>
{% include_relative combine/index.md %}
```

To include the index.md links but we need to bring in everything from those folders and I couldn't quite seem to figure out how. 

# 2 

By adding in some custom html it looks like some of the jekyll internal link stuff isn't displaying correctly? Just raw text, not a link...

Screen Shot 2020-08-11 at 10 44 54 AM

**Comment by DarkMetroid** [comment]
For the markdown parsing it looks like we have to enable it to happen in html (see: https://stackoverflow.com/questions/27859082/markdown-is-not-being-rendered-on-jekyll-site)

Testing in `_config.yml`
`# Parsing
kramdown:
  toc_levels: "2"
  parse_block_html: true
`
That seems to wrok.

Seems like for includes the parent page's values are used, so
`color block`
in `/en/data/` actually uses `/en/guide/`. Just changing the urls to be explicit should work, but that still doesn't fix the Jekyll front-matter appearing on the page. That said, maybe we can just delete the Jekyll front-matter? I don't think we actually need it there.

**Comment by MayaGans** [comment]
Oh also this closes issue #318 😊

**Comment by MayaGans** [comment]
Thanks so much for all your help with this @DarkMetroid!

So now I'm trying to get `GUIDE` to generate dropdowns (that look like the MUI dropdowns in tidyblocks hopefully eventually...) will go to either `/en/guide` or `/es/guide` but flailing because they use YAML and we don't - we just use `nav.html`

https://mycyberuniverse.com/jekyll-bootstrap-dynamic-navigation-highlighting-active-element.html

Maybe you have some pointers ?

**Comment by MayaGans** [comment]
GUIDE and FAQ have language dropdowns:

Screen Shot 2020-08-12 at 9 31 59 AM

**Review by DarkMetroid — APPROVED** [review]

**Pull request merged**
