### PR TITLE
Saves svg files to a zip in bulk.

### PR DESCRIPTION
**Pull request by DarkMetroid**
Turns out getting the `.length` of the svg string for the buffer doesn't work every time because there are multi-byte characters in some svgs >.>

That said works now, and downloads everything to a zip file.

### CODE REVIEW

**Review by MayaGans — APPROVED** [review]
Pulled down and tested on blocks and multiple blocks - looks great!!

**Comment by MayaGans** [comment]
I pulled this down and it looks like this allows the user to download their workspace as SVG [SO COOL!!!!] Should I use this to create a svg file for every block and put them in `img` directories per language? Or is that something we could automate somehow?

**Comment by MayaGans** [comment]
If @gvwilson agrees we should merge I can pull this into my blog-css PR and:

1. remove all the svgs in each block folder
2. add a img folder containing all images for each language
3. replace the urls so the blocks render on the site

**Comment by gvwilson** [comment]
:+1:

**Pull request merged**
