### PR TITLE
A proposal for project governance

### PR DESCRIPTION
**Pull request by gvwilson**
Please add thoughts in the thread below.

### CODE REVIEW

**Comment by DarkMetroid** [comment]
No objections, seems reasonable for me

**Comment by demar01** [comment]
Nothing to add, it looks good to me

**Comment by gioferreira** [comment]
I'm glad to be invited to contribute to this discussion on project governance.
I really like the Martha's Rules approach.

**Comment by MayaGans** [comment]
I like this too!

**Pull request merged**
