### PR TITLE
Adding Spanish to plots

### PR DESCRIPTION
**Pull request by demar01**
Hi
I translated to Spanish some entries on /blocks/plot.js adding "es:" language for those translations.
Please let me know if this makes sense and I could to same to other .js files.
Cheers

### CODE REVIEW

**Comment by gvwilson** [comment]
Thank you very much - we'll review it today.

**Comment by gvwilson** [comment]
This looks good to me - I will merge it right away. Please have a look at the other files in `./blocks/*.js` that have `MSG` tables - translations for them would be very welcome. We should have support for displaying blocks in Español in a couple of days to test this properly.

**Comment by demar01** [comment]
Sounds great! Will do the rest of translations shortly.

**Comment by gvwilson** [comment]
Thanks - a couple of comments I spotted while merging:
1. We need commas `,` separating the entries inside each table (example below).
2. Please do not include blank lines.

So an entry looks like:

```
demar01: {
  en: "one",
  es: "uno"
}
```

(Note the comma at the end of the `en` line.)

**Comment by demar01** [comment]
I see. Will include comma separating languages. 
And no blank lines.

**Pull request merged**
